// lib/fund-recommendations-data.ts
//
// SINGLE SOURCE OF TRUTH for the real-fund recommendations shown after the
// risk-profile quiz. Every fund here is a REAL, currently-active Indian
// mutual-fund scheme — researched via web search (AMC factsheets/official
// sites, Value Research, Tickertape, Groww, IndMoney) rather than invented,
// consistent with this project's "never fabricate a number" rule.
//
// Data is a point-in-time snapshot (see `asOf` per fund) — fund allocations,
// NAVs and returns drift constantly, so this should be refreshed periodically
// rather than treated as permanently current. Where sources disagreed and
// could not be reconciled, or a figure genuinely could not be found, the
// field is simply omitted (undefined) rather than guessed — never invent a
// number to fill a gap here.
//
// Each risk tier intentionally lists funds from DIFFERENT fund houses with
// SIMILAR risk/return characteristics but DIFFERENT asset-allocation mixes,
// so a user can compare and pick based on their own priorities (e.g. more
// conservative within the band vs. more aggressive within the band).
//
// topHoldings now lists each fund's real disclosed holdings out to roughly
// 60% cumulative portfolio weight (not just a top-3-5 sample) — see
// `holdingsCoverageNote` on each fund for the exact coverage actually
// achieved (real disclosures vary: some funds are concentrated enough that
// 15 holdings clears 60%, others need 30-40). This still is NOT the fund's
// full portfolio (most hold 80-330+ line items) — never present it as a
// complete or replicable blueprint of the fund. Every holding carries a
// `category` (equity / debt / reit_invit / other) so debt instruments,
// cash-equivalents and derivative overlays are never mistaken for stocks.
//
// Every ticker below was individually verified against NSE/exchange-listing
// sources — never guessed from the company name — and is present ONLY on
// holdings that are themselves exchange-traded (equity shares, or listed
// REIT/InvIT units) with real live-price data available via Groww's API
// (see app/api/holdings-price/route.ts and
// components/messages/fund-recommendations-card.tsx). Bonds, G-Secs, NCDs,
// CDs, SDLs and repo/cash lines have no ticker: they don't trade on an
// exchange with a live last-traded-price feed the way listed securities do.

export type RiskTierProfile = "Conservative" | "Moderate" | "Growth-oriented" | "Aggressive";

export interface HoldingTicker {
  exchange: "NSE";
  /** Real, verified NSE trading symbol (Groww/NSE's own `trading_symbol`). */
  tradingSymbol: string;
}

export type HoldingCategory = "equity" | "debt" | "reit_invit" | "other";

export interface Holding {
  /** Holding/instrument name exactly as disclosed (bond/NCD names include
   * coupon and maturity where the AMC discloses them that way). */
  name: string;
  /** Exact disclosed weight, as a percentage (e.g. 4.49 for 4.49%). */
  weightPct: number;
  /** equity = listed stock; reit_invit = listed REIT/InvIT unit;
   * debt = bond/NCD/G-Sec/SDL/CD/debenture; other = repo, cash, net
   * receivables, derivative/hedge overlays, or an internal fund-of-fund
   * unit. Only equity and reit_invit can ever carry a `ticker`. */
  category: HoldingCategory;
  /** Present only for holdings that are themselves exchange-traded
   * (equity shares or listed REIT/InvIT units) with a verified NSE trading
   * symbol — never set for bonds/G-Secs/NCDs/debentures/repo/cash. */
  ticker?: HoldingTicker;
}

export interface FundOption {
  amc: string;
  schemeName: string;
  /** The real SEBI/AMC category this scheme is classified under. */
  category: string;
  /** Approx current equity allocation %, when disclosed by the AMC. */
  equityPct?: number;
  /** Approx current debt/other allocation %, when disclosed by the AMC. */
  debtPct?: number;
  /** Free-text nuance on allocation that a single equity/debt split can't
   * capture (e.g. market-cap mix, foreign equity, dynamic hedging). */
  allocationNote?: string;
  returns3Y?: number;
  returns5Y?: number;
  /** Used instead of returns3Y/5Y when the fund is younger than that. */
  returnsSinceInception?: number;
  riskometer: string;
  expenseRatioDirect?: number;
  /** Real disclosed holdings, out to roughly 60% cumulative weight — see
   * holdingsCoverageNote for exactly how much of the portfolio this is. */
  topHoldings: Holding[];
  /** States the actual coverage achieved for THIS fund's topHoldings, e.g.
   * "Top 21 of 117 disclosed holdings, ~60.9% of the portfolio, as of 4
   * Sept 2026." Always state real achieved coverage — some funds' real
   * disclosures top out a little under 60% (e.g. very diversified funds
   * with a fetch/session cutoff); never round this up or imply more
   * completeness than the fund actually gives. */
  holdingsCoverageNote: string;
  sourceUrl: string;
  sourceLabel: string;
  /** When the figures above were current, e.g. "Sept 2026". */
  asOf: string;
  /** Caveats specific to this one fund (source disagreements, fund age, etc). */
  note?: string;
}

export interface RiskTierFundSet {
  profile: RiskTierProfile;
  /** Caveat about the category as a whole, shown once per tier. */
  tierNote?: string;
  /**
   * General risk/downside education for this fund CATEGORY (not fund-
   * specific trading advice) — what can go wrong, in plain language, plus a
   * standing reminder that the holdings shown per fund are only its largest
   * DISCLOSED positions, not its full portfolio. This is deliberately
   * category-level, factual, and static (same reasoning as tierNote): real
   * risk education, never a numeric forecast, entry price, stop-loss, or
   * target — those require a SEBI Research Analyst registration FinBuddy
   * does not have and will not simulate having.
   */
  riskDisclosure: string;
  funds: FundOption[];
}

export const FUND_RECOMMENDATIONS: Record<RiskTierProfile, RiskTierFundSet> = {
  Conservative: {
    profile: "Conservative",
    tierNote:
      "All five funds below are SEBI-classified Conservative Hybrid Funds (10-25% equity, 75-90% debt), so they sit in the same regulatory box — the differences between them are in exactly how conservative they run within that band, their debt credit quality mix, and cost.",
    riskDisclosure:
      "Conservative Hybrid Funds are debt-heavy but not risk-free. The corporate-bond and NCD holdings carry credit risk (a rating downgrade or default hits NAV directly) and interest-rate risk (bond prices fall when interest rates rise), and even the small 10-25% equity sleeve can swing double digits in a bad year. There is no capital guarantee — NAV can and does fall, just usually by less than at higher tiers. The holdings shown for each fund above now cover roughly 60% of its disclosed portfolio (see each fund's holdingsCoverageNote for the exact figure) — useful for seeing the real shape of the portfolio, but still not the complete holding list, and never a replicable blueprint of it.",
    funds: [
      {
        amc: "ICICI Prudential Mutual Fund",
        schemeName: "ICICI Prudential Conservative Hybrid Fund",
        category: "Conservative Hybrid Fund",
        equityPct: 23.5,
        debtPct: 76.5,
        allocationNote: "Debt sleeve: ~50.5% corporate debt, ~17.6% G-Secs, rest cash/other.",
        returns3Y: 9.17,
        returns5Y: 8.69,
        riskometer: "High",
        expenseRatioDirect: 1.03,
        holdingsCoverageNote: "Top 36 of 143 disclosed holdings, ~60.3% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "GOI 6.94% 2036", weightPct: 4.49, category: "debt" },
          { name: "GOI 6.90% 2065", weightPct: 4.09, category: "debt" },
          { name: "Others (Interest Rate Swap)", weightPct: 3.72, category: "other" },
          { name: "Adani Enterprises NCD 8.70% 2028", weightPct: 2.98, category: "debt" },
          { name: "Manappuram Finance NCD 8% 2027", weightPct: 2.95, category: "debt" },
          { name: "Godrej Properties NCD 8.40% 2028", weightPct: 2.25, category: "debt" },
          { name: "NABARD Bond 7.62% 2028", weightPct: 2.24, category: "debt" },
          { name: "Yes Bank Bonds 8.00% 2026", weightPct: 1.93, category: "debt" },
          { name: "GOI 4.45% 2034", weightPct: 1.64, category: "debt" },
          { name: "ICICI Bank", weightPct: 1.59, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Vedanta NCD 9.31% 2027", weightPct: 1.51, category: "debt" },
          { name: "IndoStar Capital Finance NCD 10% 2026", weightPct: 1.49, category: "debt" },
          { name: "Eris Lifesciences NCD 8.73% 2027", weightPct: 1.49, category: "debt" },
          { name: "Eris Lifesciences NCD 8.73% 2026", weightPct: 1.49, category: "debt" },
          { name: "NABARD Bond 7.83% 2026", weightPct: 1.49, category: "debt" },
          { name: "HDFC Bank", weightPct: 1.49, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "360 One Prime NCD 2028", weightPct: 1.49, category: "debt" },
          { name: "Muthoot Finance NCD 2029", weightPct: 1.49, category: "debt" },
          { name: "Narayana Hrudayalaya NCD 8.25% 2029", weightPct: 1.49, category: "debt" },
          { name: "360 One Prime NCD 8.80% 2028", weightPct: 1.49, category: "debt" },
          { name: "Adani Power NCD 8% 2028", weightPct: 1.48, category: "debt" },
          { name: "Motilal Oswal Financial Services NCD 8.15% 2028", weightPct: 1.48, category: "debt" },
          { name: "Siddhivinayak Securitisation Trust PTC", weightPct: 1.47, category: "other" },
          { name: "Repo", weightPct: 1.4, category: "other" },
          { name: "Keystone Realtors NCD 9.5% 2028", weightPct: 1.26, category: "debt" },
          { name: "Godrej Industries NCD (I)", weightPct: 1.11, category: "debt" },
          { name: "Godrej Industries NCD (II)", weightPct: 1.11, category: "debt" },
          { name: "Axis Bank", weightPct: 1.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "SBI Life Insurance", weightPct: 0.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBILIFE" } },
          { name: "NTPC", weightPct: 0.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Vedanta NCD 9.40% 2027", weightPct: 0.9, category: "debt" },
          { name: "Ashiana Housing NCD 9.95% 2029", weightPct: 0.9, category: "debt" },
          { name: "Britannia Industries", weightPct: 0.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BRITANNIA" } },
          { name: "Prism Johnson NCD 8.60% 2029", weightPct: 0.89, category: "debt" },
          { name: "Bharti Airtel", weightPct: 0.84, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Sun Pharmaceutical Industries", weightPct: 0.81, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SUNPHARMA" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/icici-prudential-regular-savings-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Renamed from \\\"ICICI Prudential Regular Savings Fund\\\" in the AMC's Aug 2026 scheme-renaming exercise; same scheme.",
      },
      {
        amc: "Kotak Mahindra Mutual Fund",
        schemeName: "Kotak Conservative Hybrid Fund",
        category: "Conservative Hybrid Fund",
        equityPct: 23.18,
        debtPct: 76.82,
        allocationNote: "Equity split: large cap 15.2%, mid cap 6.7%, small cap 1.3%.",
        returns3Y: 8.95,
        returns5Y: 8.8,
        riskometer: "High",
        expenseRatioDirect: 0.59,
        holdingsCoverageNote: "Top 22 of 130 disclosed holdings, ~60.7% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "Repo", weightPct: 11.28, category: "other" },
          { name: "GOI 7.24% 2055", weightPct: 7.14, category: "debt" },
          { name: "GOI 6.90% 2065", weightPct: 6.63, category: "debt" },
          { name: "JTPM Metal Traders NCD 2030", weightPct: 3.76, category: "debt" },
          { name: "NABARD Bond 7.44% 2029", weightPct: 3.5, category: "debt" },
          { name: "LIC Housing Finance NCD", weightPct: 2.62, category: "debt" },
          { name: "Siddhivinayak Securitisation Trust PTC", weightPct: 2.58, category: "other" },
          { name: "Shivshakti Securitisation Trust PTC", weightPct: 2.56, category: "other" },
          { name: "National Housing Bank Bond 6.80% 2032", weightPct: 2.06, category: "debt" },
          { name: "Tamil Nadu SDL 7.80% 2041", weightPct: 1.78, category: "debt" },
          { name: "Tamil Nadu SDL 7.21% 2032", weightPct: 1.76, category: "debt" },
          { name: "360 One Prime NCD 2028", weightPct: 1.75, category: "debt" },
          { name: "Muthoot Finance NCD 2029", weightPct: 1.75, category: "debt" },
          { name: "Andhra Pradesh State Beverages Corp Bond 9.15% 2027", weightPct: 1.67, category: "debt" },
          { name: "ICICI Bank", weightPct: 1.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "State Bank of India", weightPct: 1.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Bihar SDL 7.45% 2034", weightPct: 1.23, category: "debt" },
          { name: "Karnataka SDL 7.58% 2040", weightPct: 1.23, category: "debt" },
          { name: "Adani Power NCD 8.20% 2029", weightPct: 1.22, category: "debt" },
          { name: "Telangana State Industrial Infra Corp NCD 9.35% 2027", weightPct: 1.16, category: "debt" },
          { name: "Maruti Suzuki India", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Bharti Airtel", weightPct: 1.13, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/kotak-debt-hybrid-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Formerly \\\"Kotak Debt Hybrid Fund\\\"; same scheme, now displayed as Conservative Hybrid Fund.",
      },
      {
        amc: "Canara Robeco Mutual Fund",
        schemeName: "Canara Robeco Conservative Hybrid Fund",
        category: "Conservative Hybrid Fund",
        equityPct: 24.75,
        debtPct: 75.25,
        allocationNote: "Equity split: large cap 16.0%, small cap 7.6%, mid cap 1.2%.",
        returns3Y: 8.12,
        returns5Y: 7.18,
        riskometer: "Moderately High",
        expenseRatioDirect: 0.56,
        holdingsCoverageNote: "Top 18 of 81 disclosed holdings, ~61.3% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "Repo", weightPct: 11.11, category: "other" },
          { name: "GOI 4.45% 2034", weightPct: 4.14, category: "debt" },
          { name: "GOI 6.94% 2036", weightPct: 4.06, category: "debt" },
          { name: "Bajaj Housing Finance NCD 7.02%", weightPct: 3.42, category: "debt" },
          { name: "HDFC Bank Debenture 9%", weightPct: 2.97, category: "debt" },
          { name: "Tata Capital Housing Finance NCD 8.04%", weightPct: 2.89, category: "debt" },
          { name: "SIDBI Bond 7.79%", weightPct: 2.89, category: "debt" },
          { name: "LIC Housing Finance NCD 7.75%", weightPct: 2.89, category: "debt" },
          { name: "08.08% KMPL Bond 2027", weightPct: 2.89, category: "debt" },
          { name: "Bajaj Finance NCD 8.12%", weightPct: 2.89, category: "debt" },
          { name: "Power Finance Corp Bond 7.42%", weightPct: 2.88, category: "debt" },
          { name: "LIC Housing Finance NCD 7.68%", weightPct: 2.88, category: "debt" },
          { name: "Sundaram Finance CP", weightPct: 2.86, category: "debt" },
          { name: "Punjab National Bank CD", weightPct: 2.86, category: "debt" },
          { name: "NABARD CD", weightPct: 2.78, category: "debt" },
          { name: "GOI Floating Rate Bond", weightPct: 2.39, category: "debt" },
          { name: "Indian Oil Corp Bond 6.14%", weightPct: 2.29, category: "debt" },
          { name: "ICICI Bank", weightPct: 2.24, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/canara-robeco-monthly-i-come-plan-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Expense ratio sources disagreed (0.56% vs 0.75%); using the Value Research figure. Scheme is still branded \\\"Monthly Income Plan\\\" on some platforms; same fund.",
      },
      {
        amc: "SBI Mutual Fund",
        schemeName: "SBI Conservative Hybrid Fund",
        category: "Conservative Hybrid Fund",
        equityPct: 23.21,
        debtPct: 76.79,
        allocationNote: "Debt sleeve: 64.0% corporate debt, 12.8% G-Secs/cash/CDs.",
        returns3Y: 8.69,
        returns5Y: 8.5,
        riskometer: "Moderately High",
        expenseRatioDirect: 1.23,
        holdingsCoverageNote: "Top 31 of 106 disclosed holdings, ~60.3% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "NABARD Bond 7.16% 2029", weightPct: 3.16, category: "debt" },
          { name: "Repo", weightPct: 3.12, category: "other" },
          { name: "Sundaram Finance NCD 7.75%", weightPct: 2.94, category: "debt" },
          { name: "Adani Power NCD 8%", weightPct: 2.92, category: "debt" },
          { name: "JTPM Metal Traders NCD", weightPct: 2.89, category: "debt" },
          { name: "Torrent Power NCD", weightPct: 2.47, category: "debt" },
          { name: "Tata Power NCD 7.50%", weightPct: 2.45, category: "debt" },
          { name: "Tamil Nadu SDL 7.52%", weightPct: 2.36, category: "debt" },
          { name: "JSW Kalinga Steel Debenture", weightPct: 2.27, category: "debt" },
          { name: "Aditya Birla Renewables NCD 8.6%", weightPct: 2.21, category: "debt" },
          { name: "LIC Housing Finance NCD 7.58%", weightPct: 2.2, category: "debt" },
          { name: "REC Ltd Bond 7.30%", weightPct: 2.2, category: "debt" },
          { name: "Cholamandalam Investment NCD 9.05%", weightPct: 1.98, category: "debt" },
          { name: "GMR Airports Bond", weightPct: 1.82, category: "debt" },
          { name: "Bharti Telecom NCD 8.75% (I)", weightPct: 1.79, category: "debt" },
          { name: "Kingfa Science & Technology (India)", weightPct: 1.77, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KINGFA" } },
          { name: "LIC Housing Finance NCD", weightPct: 1.71, category: "debt" },
          { name: "Godrej Industries NCD 7.54%", weightPct: 1.69, category: "debt" },
          { name: "Motilal Oswal Finvest Bond 8.80%", weightPct: 1.68, category: "debt" },
          { name: "Biocon", weightPct: 1.58, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BIOCON" } },
          { name: "Asian Paints", weightPct: 1.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ASIANPAINT" } },
          { name: "Bharti Telecom NCD 8.75% (II)", weightPct: 1.49, category: "debt" },
          { name: "NABARD Bond 7.53%", weightPct: 1.47, category: "debt" },
          { name: "Bajaj Housing Finance NCD 7.53%", weightPct: 1.47, category: "debt" },
          { name: "MTNL Bond 7.87%", weightPct: 1.46, category: "debt" },
          { name: "Muthoot Finance NCD 8.45%", weightPct: 1.46, category: "debt" },
          { name: "Bajaj Finserv", weightPct: 1.29, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJAJFINSV" } },
          { name: "ICICI Bank", weightPct: 1.29, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Tata Projects NCD 8.47%", weightPct: 1.23, category: "debt" },
          { name: "Axis Bank", weightPct: 1.22, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Shivshakti Securitisation Trust PTC", weightPct: 1.2, category: "other" },
        ],
        sourceUrl: "https://groww.in/mutual-funds/sbi-magnum-monthly-i-come-plan-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Scheme is still branded \\\"Magnum Monthly Income Plan\\\" on some platforms; same fund as SBI Conservative Hybrid Fund.",
      },
      {
        amc: "HDFC Mutual Fund",
        schemeName: "HDFC Conservative Hybrid Fund",
        category: "Conservative Hybrid Fund",
        equityPct: 19.9,
        debtPct: 79.8,
        returns3Y: 7.71,
        returns5Y: 8.07,
        returnsSinceInception: 9.43,
        riskometer: "Moderately High",
        expenseRatioDirect: 1.17,
        holdingsCoverageNote: "Top 34 of 112 disclosed holdings, ~60.3% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "GOI 7.34% 2064", weightPct: 4.18, category: "debt" },
          { name: "GOI 7.23% 2039", weightPct: 3.16, category: "debt" },
          { name: "GOI 7.09% 2054", weightPct: 2.95, category: "debt" },
          { name: "GOI 6.90% 2065", weightPct: 2.82, category: "debt" },
          { name: "IRFC Bond 8.30%", weightPct: 2.53, category: "debt" },
          { name: "GOI 4.45% 2034", weightPct: 2.37, category: "debt" },
          { name: "Torrent Power NCD 8.10%", weightPct: 2.33, category: "debt" },
          { name: "GOI 7.30% 2053", weightPct: 2.26, category: "debt" },
          { name: "GOI 7.24% 2055", weightPct: 2.25, category: "debt" },
          { name: "ICICI Bank", weightPct: 2.21, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Net Current Assets", weightPct: 1.89, category: "other" },
          { name: "Altius Telecom Infrastructure Trust NCD 7.45%", weightPct: 1.69, category: "debt" },
          { name: "HDFC Bank", weightPct: 1.61, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "NHAI Bond 8.27%", weightPct: 1.58, category: "debt" },
          { name: "Pipeline Infrastructure NCD 7.96%", weightPct: 1.56, category: "debt" },
          { name: "Bajaj Housing Finance NCD 8.05%", weightPct: 1.56, category: "debt" },
          { name: "GOI 6.68% 2031", weightPct: 1.55, category: "debt" },
          { name: "Power Finance Corp Bond 7.41%", weightPct: 1.54, category: "debt" },
          { name: "HUDCO NCD 7.37%", weightPct: 1.54, category: "debt" },
          { name: "Muthoot Finance NCD", weightPct: 1.54, category: "debt" },
          { name: "360 One Prime NCD", weightPct: 1.54, category: "debt" },
          { name: "REC Ltd Bond 6.90%", weightPct: 1.52, category: "debt" },
          { name: "IRFC Bond 6.89%", weightPct: 1.52, category: "debt" },
          { name: "Muthoot Finance NCD 7.85%", weightPct: 1.52, category: "debt" },
          { name: "State Bank of India", weightPct: 1.42, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Axis Bank", weightPct: 1.24, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "GOI 7.09% 2074", weightPct: 1.16, category: "debt" },
          { name: "IRFC Bond 7.64%", weightPct: 1.1, category: "debt" },
          { name: "GOI 7.10% 2034", weightPct: 1.1, category: "debt" },
          { name: "GOI 7.36% 2052", weightPct: 1.07, category: "debt" },
          { name: "Siddhivinayak Securitisation Trust PTC", weightPct: 1.07, category: "other" },
          { name: "Reliance Industries", weightPct: 1.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "GOI 7.26% 2033", weightPct: 0.95, category: "debt" },
          { name: "GOI 6.79% 2034", weightPct: 0.93, category: "debt" },
        ],
        sourceUrl: "https://groww.in/mutual-funds/hdfc-monthly-i-come-plan-long-term-plan-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Formerly \\\"HDFC Hybrid Debt Fund\\\"; same scheme. Lowest equity tilt of the five, the most conservative option in this band.",
      },
    ],
  },

  Moderate: {
    profile: "Moderate",
    tierNote:
      "SEBI's true \"Balanced Hybrid Fund\" category (a fixed 40-60% equity mandate) is genuinely rare in India — only a handful of AMCs have ever launched one, most only in 2026. To give a real choice of five, this tier combines one true Balanced Hybrid Fund with four Balanced Advantage / Dynamic Asset Allocation Funds, which manage their NET equity exposure dynamically and often run higher than 60% when markets look attractively valued — worth knowing before assuming these all sit strictly in the 40-60% band at every point in time.",
    riskDisclosure:
      "The 40-70%+ equity sleeve in these funds means a market downturn can meaningfully dent NAV even though the fund isn't pure equity. Balanced Advantage Funds try to cushion this by dynamically cutting equity exposure when valuations look stretched — but that market-timing model can also get it wrong and lag a rising market, which is its own risk. Neither hybrid category guarantees a minimum return, and the debt sleeve still carries interest-rate and credit risk. The holdings shown for each fund above now cover roughly 60% of its disclosed portfolio (see each fund's holdingsCoverageNote for the exact figure) — useful for seeing the real shape of the portfolio, but still not the complete holding list, and never a replicable blueprint of it.",
    funds: [
      {
        amc: "WhiteOak Capital Mutual Fund",
        schemeName: "WhiteOak Capital Balanced Hybrid Fund",
        category: "Balanced Hybrid Fund (true 40-60% equity mandate)",
        equityPct: 56.5,
        debtPct: 43.5,
        returnsSinceInception: 12.48,
        riskometer: "Very High",
        expenseRatioDirect: 0.72,
        holdingsCoverageNote: "Top 28 disclosed holdings, ~60.0% of the portfolio, as of 31 Jul 2026.",
        topHoldings: [
          { name: "ICICI Bank", weightPct: 5.25, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Others (CBLO)", weightPct: 4.82, category: "other" },
          { name: "HDFC Bank", weightPct: 3.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Bajaj Finance NCD 8.06% 2029", weightPct: 3.43, category: "debt" },
          { name: "GOI 6.94% 2036", weightPct: 2.93, category: "debt" },
          { name: "HDFC Bank CD 2026", weightPct: 2.68, category: "debt" },
          { name: "Bharti Airtel", weightPct: 2.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "LIC Housing Finance NCD", weightPct: 2.39, category: "debt" },
          { name: "Nexus Select Trust", weightPct: 2, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "NXST" } },
          { name: "Nestle India", weightPct: 1.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NESTLEIND" } },
          { name: "Reliance Industries NCD 8.95% 2028", weightPct: 1.77, category: "debt" },
          { name: "NABARD Bond 7.64% 2029", weightPct: 1.72, category: "debt" },
          { name: "Power Finance Corp Bond 7.40% 2030", weightPct: 1.71, category: "debt" },
          { name: "Bajaj Housing Finance NCD 7.83% 2029", weightPct: 1.71, category: "debt" },
          { name: "NABARD Bond 7.40% 2030", weightPct: 1.71, category: "debt" },
          { name: "SIDBI Bond 7.39% 2030", weightPct: 1.71, category: "debt" },
          { name: "Cholamandalam Investment NCD 8.19% 2027", weightPct: 1.7, category: "debt" },
          { name: "Muthoot Finance NCD 7.88% 2028", weightPct: 1.68, category: "debt" },
          { name: "Bajaj Housing Finance NCD 7.02% 2028", weightPct: 1.68, category: "debt" },
          { name: "Mahindra & Mahindra", weightPct: 1.62, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "GOI 6.28% 2032", weightPct: 1.61, category: "debt" },
          { name: "Embassy Office Parks REIT", weightPct: 1.61, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "EMBASSY" } },
          { name: "Reliance Industries", weightPct: 1.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.41, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Cholamandalam Investment NCD 8.40% 2027", weightPct: 1.36, category: "debt" },
          { name: "Bharat Electronics", weightPct: 1.34, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BEL" } },
          { name: "Kotak Mahindra Bank", weightPct: 1.31, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Maruti Suzuki India", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/whiteoak-capital-balanced-hybrid-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "31 Jul 2026",
        note: "Launched Oct 2023, so under 3 years old — no 3Y/5Y CAGR yet, since-inception figure shown instead. One of only two Balanced Hybrid Funds in India with any real track record.",
      },
      {
        amc: "HDFC Mutual Fund",
        schemeName: "HDFC Balanced Advantage Fund",
        category: "Hybrid – Dynamic Asset Allocation Fund (marketed as \\\"Balanced Advantage\\\")",
        equityPct: 65,
        debtPct: 35,
        returns3Y: 12.3,
        returns5Y: 15.04,
        riskometer: "Very High",
        expenseRatioDirect: 0.64,
        holdingsCoverageNote: "Top 40 of 330 disclosed holdings, ~59.1% of the portfolio (just short of the usual 60% mark — this fund's 330-line disclosure spreads weight very thin; this is the fullest slice pulled), as of 4 Sept 2026.",
        topHoldings: [
          { name: "ICICI Bank", weightPct: 5.23, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "HDFC Bank", weightPct: 4.34, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Reliance Industries", weightPct: 3.81, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "State Bank of India", weightPct: 3.34, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Bharti Airtel", weightPct: 3.17, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Axis Bank", weightPct: 2.52, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Larsen & Toubro", weightPct: 2.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "NTPC", weightPct: 2.05, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "GOI 7.18% 2033", weightPct: 1.99, category: "debt" },
          { name: "Coal India", weightPct: 1.64, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "COALINDIA" } },
          { name: "Infosys", weightPct: 1.57, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Sun Pharmaceutical Industries", weightPct: 1.54, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SUNPHARMA" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Maruti Suzuki India", weightPct: 1.5, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Kotak Mahindra Bank", weightPct: 1.41, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Lupin", weightPct: 1.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LUPIN" } },
          { name: "HCL Technologies", weightPct: 1.26, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Tata Consultancy Services", weightPct: 1.18, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TCS" } },
          { name: "InterGlobe Aviation", weightPct: 1.16, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "ITC", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "Repo", weightPct: 1.04, category: "other" },
          { name: "Net Current Assets", weightPct: 0.95, category: "other" },
          { name: "SBI Life Insurance", weightPct: 0.93, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBILIFE" } },
          { name: "GOI 7.18% 2037", weightPct: 0.93, category: "debt" },
          { name: "Mahindra & Mahindra", weightPct: 0.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "GAIL (India)", weightPct: 0.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GAIL" } },
          { name: "Hyundai Motor India", weightPct: 0.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HYUNDAI" } },
          { name: "Embassy Office Parks REIT", weightPct: 0.79, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "EMBASSY" } },
          { name: "Power Finance Corp", weightPct: 0.73, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "PFC" } },
          { name: "GOI 7.34% 2064", weightPct: 0.71, category: "debt" },
          { name: "GOI 7.10% 2034", weightPct: 0.7, category: "debt" },
          { name: "Bank of Baroda", weightPct: 0.68, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BANKBARODA" } },
          { name: "Tata Steel", weightPct: 0.67, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TATASTEEL" } },
          { name: "Divi's Laboratories", weightPct: 0.66, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIVISLAB" } },
          { name: "Apar Industries", weightPct: 0.64, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "APARINDS" } },
          { name: "Hindustan Petroleum Corp", weightPct: 0.64, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HINDPETRO" } },
          { name: "Bharat Petroleum Corp", weightPct: 0.62, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BPCL" } },
          { name: "IndusInd Bank", weightPct: 0.61, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDUSINDBK" } },
          { name: "LIC Housing Finance NCD 7.57%", weightPct: 0.6, category: "debt" },
          { name: "REC Ltd", weightPct: 0.59, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RECLTD" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/hdfc-balanced-advantage-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "India's largest hybrid fund by AUM. Runs meaningfully above the 40-60% moderate band — best thought of as \\\"moderate-to-growth\\\" in practice, not strictly moderate.",
      },
      {
        amc: "ICICI Prudential Mutual Fund",
        schemeName: "ICICI Prudential Balanced Advantage Fund",
        category: "Hybrid – Dynamic Asset Allocation Fund (marketed as \\\"Balanced Advantage\\\")",
        equityPct: 70.57,
        debtPct: 15.4,
        allocationNote: "Remainder: ~4.9% cash & equivalents, ~4.0% REITs/InvITs.",
        returns3Y: 11.87,
        returns5Y: 11.15,
        riskometer: "Very High",
        expenseRatioDirect: 0.71,
        holdingsCoverageNote: "Top 29 disclosed holdings, ~60.1% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "TVS Motor Company", weightPct: 6.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TVSMOTOR" } },
          { name: "Repo", weightPct: 4.49, category: "other" },
          { name: "ICICI Bank", weightPct: 3.74, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "HDFC Bank", weightPct: 3.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Embassy Office Parks REIT", weightPct: 2.83, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "EMBASSY" } },
          { name: "Others (Interest Rate Swap)", weightPct: 2.82, category: "other" },
          { name: "Cash Margin", weightPct: 2.76, category: "other" },
          { name: "Reliance Industries", weightPct: 2.71, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Infosys", weightPct: 2.55, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Larsen & Toubro", weightPct: 2.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Eternal (formerly Zomato)", weightPct: 2.08, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Maruti Suzuki India", weightPct: 2.05, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "State Bank of India", weightPct: 1.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Axis Bank", weightPct: 1.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "InterGlobe Aviation", weightPct: 1.48, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "Kotak Mahindra Bank", weightPct: 1.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "HDFC Bank CD 2027", weightPct: 1.42, category: "debt" },
          { name: "Trent", weightPct: 1.42, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TRENT" } },
          { name: "Titan Company", weightPct: 1.41, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TITAN" } },
          { name: "Britannia Industries", weightPct: 1.31, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BRITANNIA" } },
          { name: "Avenue Supermarts", weightPct: 1.21, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DMART" } },
          { name: "Net Current Assets", weightPct: 1.17, category: "other" },
          { name: "HCL Technologies", weightPct: 1.14, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Bajaj Finance", weightPct: 1.13, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "Bharti Airtel", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "GOI 15-Apr-2065", weightPct: 1.07, category: "debt" },
          { name: "Mahindra & Mahindra", weightPct: 1.06, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "GOI 11-May-2036", weightPct: 1.05, category: "debt" },
          { name: "NTPC", weightPct: 1.05, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/icici-prudential-balanced-advantage-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
      },
      {
        amc: "Kotak Mahindra Mutual Fund",
        schemeName: "Kotak Balanced Advantage Fund",
        category: "Hybrid – Dynamic Asset Allocation Fund (marketed as \\\"Balanced Advantage\\\")",
        equityPct: 65.16,
        debtPct: 34.84,
        allocationNote: "Debt+cash split roughly even (~17.75% debt, ~17.1% cash/equivalents).",
        returns5Y: 9.38,
        riskometer: "Very High",
        expenseRatioDirect: 0.54,
        holdingsCoverageNote: "Top 25 of 268 disclosed holdings, ~60.1% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "Cash Margin", weightPct: 8.3, category: "other" },
          { name: "GOI 7.34% 2064", weightPct: 5.82, category: "debt" },
          { name: "ICICI Bank", weightPct: 5.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Repo", weightPct: 4.68, category: "other" },
          { name: "State Bank of India", weightPct: 3.76, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Reliance Industries", weightPct: 3.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "HDFC Bank", weightPct: 3.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Bharti Airtel", weightPct: 2.49, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Larsen & Toubro", weightPct: 2, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Bajaj Finance", weightPct: 2, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "Infosys", weightPct: 1.66, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Solar Industries India", weightPct: 1.54, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SOLARINDS" } },
          { name: "Mahindra & Mahindra", weightPct: 1.53, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Maruti Suzuki India", weightPct: 1.39, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Bank of Baroda CD", weightPct: 1.38, category: "debt" },
          { name: "Axis Bank", weightPct: 1.28, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Adani Ports & SEZ", weightPct: 1.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ADANIPORTS" } },
          { name: "JTPM Metal Traders NCD", weightPct: 1.23, category: "debt" },
          { name: "GE Vernova T&D India", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GVT&D" } },
          { name: "Brookfield India Real Estate Trust", weightPct: 1.13, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "BIRET" } },
          { name: "National Housing Bank Bond 6.80%", weightPct: 1.13, category: "debt" },
          { name: "Kotak Mahindra Bank", weightPct: 1.11, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Mphasis", weightPct: 1.06, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MPHASIS" } },
          { name: "InterGlobe Aviation", weightPct: 1.05, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/kotak-balanced-advantage-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Lowest-cost option in this tier. Verified Direct-plan 3Y CAGR not found; 5Y shown instead.",
      },
      {
        amc: "Nippon India Mutual Fund",
        schemeName: "Nippon India Balanced Advantage Fund",
        category: "Hybrid – Dynamic Asset Allocation Fund (marketed as \\\"Balanced Advantage\\\")",
        returns3Y: 11.38,
        returns5Y: 10.05,
        riskometer: "Very High",
        expenseRatioDirect: 0.55,
        holdingsCoverageNote: "Top 25 of 199 disclosed holdings, ~60.6% of the portfolio among long positions (a separate batch of short index/stock-futures hedge overlays, not additional long exposure, is excluded from this count), as of 4 Sept 2026.",
        topHoldings: [
          { name: "Cash Margin", weightPct: 10.82, category: "other" },
          { name: "ICICI Bank", weightPct: 6.13, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "HDFC Bank", weightPct: 6.02, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Reliance Industries", weightPct: 2.64, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "State Bank of India", weightPct: 2.6, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Infosys", weightPct: 2.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Bharti Airtel", weightPct: 2.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Repo", weightPct: 2.43, category: "other" },
          { name: "Axis Bank", weightPct: 2.4, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Mahindra & Mahindra", weightPct: 2.25, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Bajaj Finance", weightPct: 1.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "Larsen & Toubro", weightPct: 1.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.69, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "NTPC", weightPct: 1.65, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Cube Highways Trust", weightPct: 1.52, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "CUBEINVIT" } },
          { name: "NABARD Bond 7.48% 2028", weightPct: 1.52, category: "debt" },
          { name: "Kotak Mahindra Bank", weightPct: 1.43, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Mindspace Business Parks REIT", weightPct: 1.28, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "MINDSPACE" } },
          { name: "Muthoot Finance NCD", weightPct: 1.26, category: "debt" },
          { name: "Samvardhana Motherson International", weightPct: 1.1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MOTHERSON" } },
          { name: "Star Health & Allied Insurance", weightPct: 1.04, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "STARHEALTH" } },
          { name: "Godrej Consumer Products", weightPct: 1.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GODREJCP" } },
          { name: "FSN E-Commerce Ventures (Nykaa)", weightPct: 1.02, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NYKAA" } },
          { name: "ITC", weightPct: 1.02, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "InterGlobe Aviation", weightPct: 0.99, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/nippon-india-balanced-advantage-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Current equity/debt split % could not be verified from available sources — omitted rather than estimated. Expense ratio also had a conflicting second figure (0.88% per one aggregator); using Value Research's 0.55%.",
      },
    ],
  },

  "Growth-oriented": {
    profile: "Growth-oriented",
    tierNote:
      "All five funds below are SEBI-classified Aggressive Hybrid Funds (65-80% equity, 20-35% debt) from five different fund houses — same regulatory category, different equity tilt within the band and different debt/equity holdings.",
    riskDisclosure:
      "Aggressive Hybrid Funds hold 65-80% equity, so they move largely in line with the stock market — a sharp correction shows up directly in NAV, and there's no capital protection. The 20-35% debt sleeve softens but doesn't eliminate this. Some funds here carry extra fund-specific concentration risk beyond the category average (see each fund's own note above, e.g. heavy exposure to one business group or sector) — that's a real, additional risk on top of general market risk, not a bonus. The holdings shown for each fund above now cover roughly 60% of its disclosed portfolio (see each fund's holdingsCoverageNote for the exact figure) — useful for seeing the real shape of the portfolio, but still not the complete holding list, and never a replicable blueprint of it.",
    funds: [
      {
        amc: "SBI Mutual Fund",
        schemeName: "SBI Aggressive Hybrid Fund",
        category: "Aggressive Hybrid Fund",
        equityPct: 74.79,
        debtPct: 20.56,
        returns3Y: 13.05,
        returns5Y: 10.37,
        riskometer: "Very High",
        expenseRatioDirect: 0.73,
        holdingsCoverageNote: "Top 21 of 117 disclosed holdings, ~60.9% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "GOI 6.94% 2036", weightPct: 4.57, category: "debt" },
          { name: "ICICI Bank", weightPct: 4.37, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Repo", weightPct: 4.3, category: "other" },
          { name: "State Bank of India", weightPct: 3.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Adani Energy Solutions", weightPct: 3.75, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ADANIENSOL" } },
          { name: "Solar Industries India", weightPct: 3.72, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SOLARINDS" } },
          { name: "Adani Power", weightPct: 3.1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ADANIPOWER" } },
          { name: "Kotak Mahindra Bank", weightPct: 3.08, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Bajaj Finance", weightPct: 2.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "Bharti Airtel", weightPct: 2.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "MRF", weightPct: 2.54, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MRF" } },
          { name: "Adani Enterprises", weightPct: 2.53, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ADANIENT" } },
          { name: "Muthoot Finance", weightPct: 2.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MUTHOOTFIN" } },
          { name: "InterGlobe Aviation", weightPct: 2.34, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "Larsen & Toubro", weightPct: 2.3, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "HDFC Bank", weightPct: 2.28, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Reliance Industries", weightPct: 2.22, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Divi's Laboratories", weightPct: 2.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIVISLAB" } },
          { name: "Coforge", weightPct: 1.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "COFORGE" } },
          { name: "Tata Consultancy Services", weightPct: 1.87, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TCS" } },
          { name: "Shree Cement", weightPct: 1.74, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SHREECEM" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/sbi-aggressive-hybrid-fund-direct-plan-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Formerly \\\"SBI Equity Hybrid Fund\\\"; same scheme. Notable concentration in Adani-group names.",
      },
      {
        amc: "Canara Robeco Mutual Fund",
        schemeName: "Canara Robeco Aggressive Hybrid Fund",
        category: "Aggressive Hybrid Fund",
        equityPct: 79.3,
        debtPct: 20.7,
        returns3Y: 11.45,
        returns5Y: 9.7,
        riskometer: "Very High",
        expenseRatioDirect: 0.51,
        holdingsCoverageNote: "Top 34 of 130 disclosed holdings, ~60.1% of the portfolio, as of 25 Aug 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 5.04, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "ICICI Bank", weightPct: 4.65, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Repo", weightPct: 4.48, category: "other" },
          { name: "Axis Bank", weightPct: 3.04, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "State Bank of India", weightPct: 2.72, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Bharti Airtel", weightPct: 2.62, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Reliance Industries", weightPct: 2.5, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Power Finance Corporation", weightPct: 2.34, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "PFC" } },
          { name: "Larsen & Toubro", weightPct: 2.31, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Samvardhana Motherson International", weightPct: 2.25, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MOTHERSON" } },
          { name: "Infosys", weightPct: 2.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Bajaj Finance", weightPct: 1.6, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "KEI Industries", weightPct: 1.21, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KEI" } },
          { name: "GE Vernova T&D India", weightPct: 1.2, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GVT&D" } },
          { name: "GOI 4.45% 2034", weightPct: 1.2, category: "debt" },
          { name: "Coal India", weightPct: 1.17, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "COALINDIA" } },
          { name: "Tech Mahindra", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TECHM" } },
          { name: "JK Cement", weightPct: 1.14, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "JKCEMENT" } },
          { name: "Sun Pharmaceutical Industries", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SUNPHARMA" } },
          { name: "BSE", weightPct: 1.08, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BSE" } },
          { name: "CG Power & Industrial Solutions", weightPct: 1.07, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CGPOWER" } },
          { name: "Divi's Laboratories", weightPct: 1.06, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIVISLAB" } },
          { name: "Cholamandalam Financial Holdings", weightPct: 1.06, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CHOLAHLDNG" } },
          { name: "Indian Hotels Company", weightPct: 1.05, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDHOTEL" } },
          { name: "InterGlobe Aviation", weightPct: 1.04, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "Varun Beverages", weightPct: 1.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "VBL" } },
          { name: "Max Healthcare Institute", weightPct: 1.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MAXHEALTH" } },
          { name: "NTPC", weightPct: 1.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Titan Company", weightPct: 1.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TITAN" } },
          { name: "Oberoi Realty", weightPct: 1.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "OBEROIRLTY" } },
          { name: "TVS Motor Company", weightPct: 0.95, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TVSMOTOR" } },
          { name: "Maruti Suzuki India", weightPct: 0.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Max Financial Services", weightPct: 0.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MFSL" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/canara-robeco-balance-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "25 Aug 2026",
        note: "Formerly \\\"Canara Robeco Equity Hybrid Fund\\\"; same scheme. Highest equity tilt of the five.",
      },
      {
        amc: "DSP Mutual Fund",
        schemeName: "DSP Aggressive Hybrid Fund",
        category: "Aggressive Hybrid Fund",
        equityPct: 69.5,
        debtPct: 30.5,
        returns3Y: 10.2,
        returns5Y: 8.95,
        riskometer: "Very High",
        expenseRatioDirect: 0.78,
        holdingsCoverageNote: "Top 18 of 90 disclosed holdings, ~60.1% of the portfolio, as of 26 Aug 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 8.21, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "ICICI Bank", weightPct: 7.67, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "ITC", weightPct: 3.91, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "Mahindra & Mahindra", weightPct: 3.87, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Kotak Mahindra Bank", weightPct: 3.84, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "GOI 7.24% 2055", weightPct: 3.81, category: "debt" },
          { name: "Axis Bank", weightPct: 3.53, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Cipla", weightPct: 3.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CIPLA" } },
          { name: "GOI 6.90% 2065", weightPct: 3.26, category: "debt" },
          { name: "NTPC", weightPct: 2.95, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "SBI Life Insurance", weightPct: 2.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBILIFE" } },
          { name: "DSP Short Term Fund (internal debt fund unit)", weightPct: 2.3, category: "other" },
          { name: "Infosys", weightPct: 2.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Reverse Repo", weightPct: 2.02, category: "other" },
          { name: "Maruti Suzuki India", weightPct: 1.88, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Alkem Laboratories", weightPct: 1.67, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ALKEM" } },
          { name: "Emami", weightPct: 1.57, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "EMAMILTD" } },
          { name: "HDFC Life Insurance", weightPct: 1.43, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCLIFE" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/dsp-aggressive-hybrid-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "26 Aug 2026",
        note: "Formerly \\\"DSP Equity & Bond Fund\\\"; same scheme. Lowest equity tilt of the five, most conservative within this band.",
      },
      {
        amc: "Mirae Asset Mutual Fund",
        schemeName: "Mirae Asset Aggressive Hybrid Fund",
        category: "Aggressive Hybrid Fund",
        equityPct: 76.6,
        debtPct: 23.4,
        returns3Y: 11.73,
        returns5Y: 10.27,
        riskometer: "Very High",
        expenseRatioDirect: 0.4,
        holdingsCoverageNote: "Top 35 of 148 disclosed holdings, ~60.6% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 6, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "ICICI Bank", weightPct: 4.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "State Bank of India", weightPct: 4.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Reliance Industries", weightPct: 3.44, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Bharti Airtel", weightPct: 3.24, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Axis Bank", weightPct: 2.43, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "Torrent Pharmaceuticals NCD 7.45% 2028", weightPct: 1.98, category: "debt" },
          { name: "NTPC", weightPct: 1.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Laurus Labs", weightPct: 1.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LAURUSLABS" } },
          { name: "Repo", weightPct: 1.82, category: "other" },
          { name: "Larsen & Toubro", weightPct: 1.74, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Shriram Finance", weightPct: 1.61, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SHRIRAMFIN" } },
          { name: "Eternal (formerly Zomato)", weightPct: 1.56, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Mahindra & Mahindra", weightPct: 1.51, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Bajaj Finance", weightPct: 1.48, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "Infosys", weightPct: 1.42, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Tata Steel", weightPct: 1.3, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TATASTEEL" } },
          { name: "TVS Motor Company", weightPct: 1.29, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TVSMOTOR" } },
          { name: "GOI 7.10% 2034", weightPct: 1.25, category: "debt" },
          { name: "Delhivery", weightPct: 1.19, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DELHIVERY" } },
          { name: "Ambuja Cements", weightPct: 1.14, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AMBUJACEM" } },
          { name: "Tata Consultancy Services", weightPct: 1.1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TCS" } },
          { name: "Bajaj Housing Finance NCD 7.53% 2029", weightPct: 1.05, category: "debt" },
          { name: "Muthoot Finance NCD 7.88% 2028", weightPct: 1.03, category: "debt" },
          { name: "Maruti Suzuki India", weightPct: 1.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "SBI Life Insurance", weightPct: 1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBILIFE" } },
          { name: "JSW Energy", weightPct: 0.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "JSWENERGY" } },
          { name: "Titan Company", weightPct: 0.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TITAN" } },
          { name: "Glenmark Pharmaceuticals", weightPct: 0.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GLENMARK" } },
          { name: "Multi Commodity Exchange of India", weightPct: 0.94, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MCX" } },
          { name: "Bharat Electronics", weightPct: 0.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BEL" } },
          { name: "Avenue Supermarts", weightPct: 0.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DMART" } },
          { name: "Sona BLW Precision Forgings", weightPct: 0.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SONACOMS" } },
          { name: "Vedanta Aluminium Metal", weightPct: 0.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "VAML" } },
          { name: "LG Electronics India", weightPct: 0.81, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LGEINDIA" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/mirae-asset-aggressive-hybrid-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Lowest-cost option in this tier by a wide margin.",
      },
      {
        amc: "UTI Mutual Fund",
        schemeName: "UTI Aggressive Hybrid Fund",
        category: "Aggressive Hybrid Fund",
        equityPct: 74.3,
        debtPct: 25.7,
        returns3Y: 11.39,
        returns5Y: 11.48,
        riskometer: "Very High",
        expenseRatioDirect: 1.0,
        holdingsCoverageNote: "Top 33 of 137 disclosed holdings, ~60.1% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 6.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "ICICI Bank", weightPct: 5.63, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Infosys", weightPct: 3.79, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Reliance Industries", weightPct: 3.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Larsen & Toubro", weightPct: 3.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Bharti Airtel", weightPct: 3, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "State Bank of India", weightPct: 2.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "ITC", weightPct: 2.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "Net Current Assets", weightPct: 2.13, category: "other" },
          { name: "Power Grid Corporation of India", weightPct: 1.79, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "POWERGRID" } },
          { name: "Shriram Finance", weightPct: 1.73, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SHRIRAMFIN" } },
          { name: "Mahindra & Mahindra", weightPct: 1.61, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Hero Motocorp", weightPct: 1.43, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HEROMOTOCO" } },
          { name: "HCL Technologies", weightPct: 1.39, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Vedanta Aluminium Metal", weightPct: 1.33, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "VAML" } },
          { name: "GOI 7.24% 2055", weightPct: 1.33, category: "debt" },
          { name: "Wipro", weightPct: 1.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "WIPRO" } },
          { name: "Info Edge (India)", weightPct: 1.24, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NAUKRI" } },
          { name: "GOI 6.90% 2065", weightPct: 1.22, category: "debt" },
          { name: "Grasim Industries", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GRASIM" } },
          { name: "InterGlobe Aviation", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "Aurobindo Pharma", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AUROPHARMA" } },
          { name: "Indus Infra Trust (formerly Bharat Highways InvIT)", weightPct: 1.02, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "INDUSINVIT" } },
          { name: "Indus Towers", weightPct: 1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDUSTOWER" } },
          { name: "Tata Power Company", weightPct: 0.99, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TATAPOWER" } },
          { name: "Caplin Point Laboratories", weightPct: 0.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CAPLIPOINT" } },
          { name: "Maruti Suzuki India", weightPct: 0.87, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Aditya Birla Capital", weightPct: 0.84, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ABCAPITAL" } },
          { name: "Sundaram Finance", weightPct: 0.84, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SUNDARMFIN" } },
          { name: "Nexus Select Trust", weightPct: 0.84, category: "reit_invit", ticker: { exchange: "NSE", tradingSymbol: "NXST" } },
          { name: "Emami", weightPct: 0.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "EMAMILTD" } },
          { name: "G R Infraprojects", weightPct: 0.83, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GRINFRA" } },
          { name: "Crompton Greaves Consumer Electricals", weightPct: 0.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CROMPTON" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/uti-balanced-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Expense ratio not conclusively reconciled across sources (0.97%-1.32% range found); ~1.0% shown as an approximate midpoint.",
      },
    ],
  },

  Aggressive: {
    profile: "Aggressive",
    tierNote:
      "All five funds below are diversified equity schemes (Flexi Cap or Multi Cap, 90-100% equity, no fixed debt allocation) from five different fund houses — the differences are in market-cap tilt (large vs. mid vs. small cap), sector concentration, and cost.",
    riskDisclosure:
      "These are pure equity schemes with no debt cushion at all — NAV moves directly with the stock market, drawdowns of 20-30%+ in a bad year are historically not unusual for Indian equity funds, and there's no floor on losses. Flexi Cap funds can shift between large/mid/small-cap at the manager's discretion, which adds manager-decision risk on top of market risk; Multi Cap funds are contractually required to hold meaningful mid- and small-cap exposure, which is typically more volatile and less liquid than large-cap. The holdings shown for each fund above now cover roughly 60% of its disclosed portfolio (see each fund's holdingsCoverageNote for the exact figure) — useful for seeing the real shape of the portfolio, but still not the complete holding list, and never a replicable blueprint of it.",
    funds: [
      {
        amc: "PPFAS Mutual Fund",
        schemeName: "Parag Parikh Flexi Cap Fund",
        category: "Flexi Cap Fund",
        allocationNote: "~8.9% in US equities (Alphabet, Amazon, Microsoft, Meta); mandate allows 0-35% foreign equity. Large/mid/small split not fixed or separately disclosed.",
        returns3Y: 13.45,
        returns5Y: 12.22,
        riskometer: "Very High",
        expenseRatioDirect: 0.53,
        holdingsCoverageNote: "Top 13 of 152 disclosed holdings, ~61.9% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 7.55, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Power Grid Corporation of India", weightPct: 5.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "POWERGRID" } },
          { name: "ITC", weightPct: 5.74, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "ICICI Bank", weightPct: 5.56, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Coal India", weightPct: 4.91, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "COALINDIA" } },
          { name: "Bajaj Holdings & Investment", weightPct: 4.85, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJAJHLDNG" } },
          { name: "Net Receivables", weightPct: 4.6, category: "other" },
          { name: "Alphabet Inc (foreign, Nasdaq-listed — not NSE-tradable)", weightPct: 4.33, category: "equity" },
          { name: "HCL Technologies", weightPct: 4.23, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Kotak Mahindra Bank", weightPct: 4.07, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Mahindra & Mahindra", weightPct: 3.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "Infosys", weightPct: 3.25, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Bharti Airtel", weightPct: 3.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/parag-parikh-long-term-value-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "India's largest active equity fund by AUM (~Rs 1.48 lakh crore). Only fund in this tier with meaningful foreign equity exposure — its Alphabet (Google) holding trades on Nasdaq, not NSE, so no ticker/live price is shown for that one line.",
      },
      {
        amc: "HDFC Mutual Fund",
        schemeName: "HDFC Flexi Cap Fund",
        category: "Flexi Cap Fund",
        allocationNote: "Large/mid/small split not disclosed as an exact percentage; described as a \\\"large-size\\\" flexi-cap fund. Heavy private-banks tilt (~24% of portfolio).",
        returns3Y: 16.4,
        returns5Y: 17.9,
        riskometer: "Very High",
        expenseRatioDirect: 0.77,
        holdingsCoverageNote: "Top 16 of 83 disclosed holdings, ~60.6% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "ICICI Bank", weightPct: 9.21, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "HDFC Bank", weightPct: 6.11, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Axis Bank", weightPct: 6.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "State Bank of India", weightPct: 4.14, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "SBI Life Insurance", weightPct: 3.56, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBILIFE" } },
          { name: "Eternal (formerly Zomato)", weightPct: 3.36, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Larsen & Toubro", weightPct: 3.16, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "Kotak Mahindra Bank", weightPct: 3.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KOTAKBANK" } },
          { name: "Repo", weightPct: 3.1, category: "other" },
          { name: "InterGlobe Aviation", weightPct: 3.02, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDIGO" } },
          { name: "Bharti Airtel", weightPct: 2.94, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Maruti Suzuki India", weightPct: 2.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "Cipla", weightPct: 2.65, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CIPLA" } },
          { name: "HCL Technologies", weightPct: 2.58, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Eicher Motors", weightPct: 2.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "EICHERMOT" } },
          { name: "Power Grid Corporation of India", weightPct: 2.26, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "POWERGRID" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/hdfc-equity-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Strongest 3Y/5Y returns of the five, but with the heaviest single-sector (private banks) concentration.",
      },
      {
        amc: "Motilal Oswal Mutual Fund",
        schemeName: "Motilal Oswal Flexi Cap Fund",
        category: "Flexi Cap Fund",
        allocationNote: "Large cap 55.5%, mid cap 31.8%, small cap 6.5%, cash 6.2% (AMC, Mar 2026).",
        returns3Y: 18.4,
        returns5Y: 12.9,
        riskometer: "Very High",
        expenseRatioDirect: 0.73,
        holdingsCoverageNote: "Top 15 of 34 disclosed holdings, ~61.6% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "Kalyan Jewellers India", weightPct: 8.79, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KALYANKJIL" } },
          { name: "Eternal (formerly Zomato)", weightPct: 5.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "CG Power & Industrial Solutions", weightPct: 5.57, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CGPOWER" } },
          { name: "Coforge", weightPct: 4.26, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "COFORGE" } },
          { name: "Shriram Finance", weightPct: 4.23, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SHRIRAMFIN" } },
          { name: "Ather Energy", weightPct: 3.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ATHERENERG" } },
          { name: "IndusInd Bank", weightPct: 3.63, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDUSINDBK" } },
          { name: "Persistent Systems", weightPct: 3.53, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "PERSISTENT" } },
          { name: "Diamond Power Infrastructure", weightPct: 3.37, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIACABS" } },
          { name: "Apollo Hospitals Enterprise", weightPct: 3.35, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "APOLLOHOSP" } },
          { name: "Aditya Infotech (CP Plus)", weightPct: 3.28, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "CPPLUS" } },
          { name: "Waaree Energies", weightPct: 3.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "WAAREEENER" } },
          { name: "Multi Commodity Exchange of India", weightPct: 2.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MCX" } },
          { name: "Onesource Specialty Pharma", weightPct: 2.78, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ONESOURCE" } },
          { name: "PG Electroplast", weightPct: 2.74, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "PGEL" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/motilal-oswal-most-focused-multicap-35-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Formerly \\\"Motilal Oswal Most Focused Multicap 35 Fund\\\"; more concentrated, higher-conviction portfolio than the other flexi-cap options here — only 34 holdings in total, so the list above already shows nearly half the entire portfolio by count.",
      },
      {
        amc: "Nippon India Mutual Fund",
        schemeName: "Nippon India Multi Cap Fund",
        category: "Multi Cap Fund",
        allocationNote: "SEBI multi-cap mandate requires a minimum 25% each in large/mid/small cap; exact current weights beyond that floor not disclosed in available sources.",
        returns3Y: 13.64,
        returns5Y: 17.44,
        riskometer: "Very High",
        expenseRatioDirect: 0.87,
        holdingsCoverageNote: "Top 34 of 116 disclosed holdings, ~60.9% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "HDFC Bank", weightPct: 7.1, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Axis Bank", weightPct: 4.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "AXISBANK" } },
          { name: "ICICI Bank", weightPct: 4.41, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ICICIBANK" } },
          { name: "Infosys", weightPct: 3.87, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INFY" } },
          { name: "Bajaj Finance", weightPct: 1.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BAJFINANCE" } },
          { name: "NTPC", weightPct: 1.86, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Linde India", weightPct: 1.85, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LINDEINDIA" } },
          { name: "Swiggy", weightPct: 1.8, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SWIGGY" } },
          { name: "Reliance Industries", weightPct: 1.78, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RELIANCE" } },
          { name: "Larsen & Toubro", weightPct: 1.77, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LT" } },
          { name: "GE Vernova T&D India", weightPct: 1.7, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "GVT&D" } },
          { name: "Max Financial Services", weightPct: 1.66, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MFSL" } },
          { name: "Samvardhana Motherson International", weightPct: 1.58, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MOTHERSON" } },
          { name: "Jubilant FoodWorks", weightPct: 1.53, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "JUBLFOOD" } },
          { name: "Mahindra & Mahindra", weightPct: 1.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "M&M" } },
          { name: "ITC", weightPct: 1.42, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "Tata Consultancy Services", weightPct: 1.4, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TCS" } },
          { name: "Tata Power Company", weightPct: 1.35, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "TATAPOWER" } },
          { name: "State Bank of India", weightPct: 1.27, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Vesuvius India", weightPct: 1.2, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "VESUVIUS" } },
          { name: "FSN E-Commerce Ventures (Nykaa)", weightPct: 1.2, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NYKAA" } },
          { name: "EIH", weightPct: 1.19, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "EIHOTEL" } },
          { name: "Voltas", weightPct: 1.15, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "VOLTAS" } },
          { name: "Avenue Supermarts", weightPct: 1.12, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DMART" } },
          { name: "HCL Technologies", weightPct: 1.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HCLTECH" } },
          { name: "Indian Hotels Company", weightPct: 1.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDHOTEL" } },
          { name: "Lupin", weightPct: 1.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "LUPIN" } },
          { name: "Dixon Technologies", weightPct: 1.09, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIXON" } },
          { name: "SBI Cards & Payment Services", weightPct: 1.04, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBICARD" } },
          { name: "Siemens Energy India", weightPct: 1.03, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ENRIN" } },
          { name: "Kennametal India", weightPct: 0.99, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KENNAMET" } },
          { name: "Balkrishna Industries", weightPct: 0.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BALKRISIND" } },
          { name: "Eternal (formerly Zomato)", weightPct: 0.98, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "Divi's Laboratories", weightPct: 0.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "DIVISLAB" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/nippon-india-multi-cap-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "One of two true Multi Cap funds in this tier — guaranteed meaningful small/mid-cap exposure by mandate, unlike flexi-cap funds where the AMC has full discretion. Genuinely diversified (largest single holding only ~7%), so this list needed nearly a third of all disclosed lines to reach 60%.",
      },
      {
        amc: "Kotak Mahindra Mutual Fund",
        schemeName: "Kotak Multicap Fund",
        category: "Multi Cap Fund",
        allocationNote: "Large cap 43.8%, mid cap 29.3%, small cap 25.9% (AMC, Jan 2026) — the most even three-way split of any fund in this tier.",
        returns3Y: 17.46,
        riskometer: "Very High",
        expenseRatioDirect: 0.49,
        holdingsCoverageNote: "Top 23 of 76 disclosed holdings, ~60.8% of the portfolio, as of 4 Sept 2026.",
        topHoldings: [
          { name: "Maruti Suzuki India", weightPct: 5.01, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "MARUTI" } },
          { name: "HDFC Bank", weightPct: 3.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HDFCBANK" } },
          { name: "Oracle Financial Services Software", weightPct: 3.77, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "OFSS" } },
          { name: "Hero Motocorp", weightPct: 3.47, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "HEROMOTOCO" } },
          { name: "IndusInd Bank", weightPct: 3.45, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDUSINDBK" } },
          { name: "State Bank of India", weightPct: 3.23, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SBIN" } },
          { name: "Indus Towers", weightPct: 3.11, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDUSTOWER" } },
          { name: "Radico Khaitan", weightPct: 2.97, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "RADICO" } },
          { name: "Power Finance Corporation", weightPct: 2.91, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "PFC" } },
          { name: "Eternal (formerly Zomato)", weightPct: 2.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ETERNAL" } },
          { name: "NTPC", weightPct: 2.46, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NTPC" } },
          { name: "Sun Pharmaceutical Industries", weightPct: 2.28, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SUNPHARMA" } },
          { name: "ITC", weightPct: 2.26, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "ITC" } },
          { name: "INDO-MIM", weightPct: 2.23, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "INDOMIM" } },
          { name: "Bank of Baroda", weightPct: 1.96, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BANKBARODA" } },
          { name: "The South Indian Bank", weightPct: 1.94, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "SOUTHBANK" } },
          { name: "NLC India", weightPct: 1.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "NLCINDIA" } },
          { name: "Bharti Airtel", weightPct: 1.92, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BHARTIARTL" } },
          { name: "Kajaria Ceramics", weightPct: 1.9, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "KAJARIACER" } },
          { name: "The Jammu & Kashmir Bank", weightPct: 1.89, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "J&KBANK" } },
          { name: "Poonawalla Fincorp", weightPct: 1.86, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "POONAWALLA" } },
          { name: "Repo", weightPct: 1.85, category: "other" },
          { name: "Bandhan Bank", weightPct: 1.67, category: "equity", ticker: { exchange: "NSE", tradingSymbol: "BANDHANBNK" } },
        ],
        sourceUrl: "https://groww.in/mutual-funds/kotak-multi-cap-fund-direct-growth",
        sourceLabel: "Groww (fund's disclosed monthly portfolio)",
        asOf: "4 Sept 2026",
        note: "Launched Sept 2021, so no 5Y CAGR yet. Lowest cost in this tier, and the most balanced large/mid/small mix.",
      },
    ],
  },
};
